const lb = [
  {
    accessible: true,
    additional_data: {tweet_id: "1412249435837509636"},
    author_followers_count: 267453,
    author_image_url: "http://pbs.twimg.com/profile_images/378800000833266807/9ed4b5e5bffc2e60da94913d51cbd666_normal.png",
    author_screen_name: "ForexLive",
    bookmarked: false,
    can_purchase: false,
    category: "op",
    cost: null,
    description: "A piece posted yesterday on Central banks said to be returning to buying gold Adding a little more to the info in that post, with the World Gold Council saying one in five central banks intend to increase their gold reserves over the next year. By...",
    disliked: false,
    domain_cached_logo_url: "https://cityfalconstaging.blob.core.windows.net/staging-container/domains/logos/7786/thumb.png?1516785678",
    domain_host: "forexlive.com",
    domain_id: 7786,
    domain_name: "Forexlive",
    duplicatesCount: 0,
    expanded_url: "https://www.forexlive.com/news/!/more-on-the-report-central-banks-eyeing-further-purchases-of-gold-20210706?utm_campaign=cityfalcon&utm_medium=cityfalcon&utm_source=cityfalcon",
    friends_count: null,
    full_text: false,
    id: 413988023,
    imageUrls: ["https://az705044.vo.msecnd.net/20190110/mnuchin-gold.png"],
    lang: "en",
    liked: false,
    limited_content: [],
    paywall: false,
    premium_plan_level: null,
    publishTime: "2021-07-06T03:17:55.000Z",
    publishTimeDiff: 2228.52043362,
    purchased: false,
    readCount: 0,
    registrationRequired: false,
    score: 55,
    showPath: "/news/stories/14c55bfb-5efb-4382-aff8-79809ea7b7a0",
    title: "More on the report central banks eyeing further purchases of gold",
    type: "Story",
    url: "https://www.forexlive.com/news/!/more-on-the-report-central-banks-eyeing-further-purchases-of-gold-20210706?utm_campaign=cityfalcon&utm_medium=cityfalcon&utm_source=cityfalcon",
    user_premium_plans: [],
    uuid: "14c55bfb-5efb-4382-aff8-79809ea7b7a0",
    uuid_title: "14c55bfb-5efb-4382-aff8-79809ea7b7a0-more-on-the-report-central-banks-eyeing-further-purchases-of",
    visibility: null,
    _highlight: null,
    _score: null,
  },
  {
    accessible: true,
    additional_data: {tweet_id: "1412249435837509636"},
    author_followers_count: 267453,
    author_image_url: "http://pbs.twimg.com/profile_images/378800000833266807/9ed4b5e5bffc2e60da94913d51cbd666_normal.png",
    author_screen_name: "ForexLive",
    bookmarked: false,
    can_purchase: false,
    category: "op",
    cost: null,
    description: "A piece posted yesterday on Central banks said to be returning to buying gold Adding a little more to the info in that post, with the World Gold Council saying one in five central banks intend to increase their gold reserves over the next year. By...",
    disliked: false,
    domain_cached_logo_url: "https://cityfalconstaging.blob.core.windows.net/staging-container/domains/logos/7786/thumb.png?1516785678",
    domain_host: "forexlive.com",
    domain_id: 7786,
    domain_name: "Forexlive",
    duplicatesCount: 0,
    expanded_url: "https://www.forexlive.com/news/!/more-on-the-report-central-banks-eyeing-further-purchases-of-gold-20210706?utm_campaign=cityfalcon&utm_medium=cityfalcon&utm_source=cityfalcon",
    friends_count: null,
    full_text: false,
    id: 413988023,
    imageUrls: ["https://az705044.vo.msecnd.net/20190110/mnuchin-gold.png"],
    lang: "en",
    liked: false,
    limited_content: [],
    paywall: false,
    premium_plan_level: null,
    publishTime: "2021-07-06T03:17:55.000Z",
    publishTimeDiff: 2228.52043362,
    purchased: false,
    readCount: 0,
    registrationRequired: false,
    score: 55,
    showPath: "/news/stories/14c55bfb-5efb-4382-aff8-79809ea7b7a0",
    title: "More on the report central banks eyeing further purchases of gold",
    type: "Story",
    url: "https://www.forexlive.com/news/!/more-on-the-report-central-banks-eyeing-further-purchases-of-gold-20210706?utm_campaign=cityfalcon&utm_medium=cityfalcon&utm_source=cityfalcon",
    user_premium_plans: [],
    uuid: "14c55bfb-5efb-4382-aff8-79809ea7b7a0",
    uuid_title: "14c55bfb-5efb-4382-aff8-79809ea7b7a0-more-on-the-report-central-banks-eyeing-further-purchases-of",
    visibility: null,
    _highlight: null,
    _score: null,
  },
  {
    accessible: true,
    additional_data: {tweet_id: "1412249435837509636"},
    author_followers_count: 267453,
    author_image_url: "http://pbs.twimg.com/profile_images/378800000833266807/9ed4b5e5bffc2e60da94913d51cbd666_normal.png",
    author_screen_name: "ForexLive",
    bookmarked: false,
    can_purchase: false,
    category: "op",
    cost: null,
    description: "A piece posted yesterday on Central banks said to be returning to buying gold Adding a little more to the info in that post, with the World Gold Council saying one in five central banks intend to increase their gold reserves over the next year. By...",
    disliked: false,
    domain_cached_logo_url: "https://cityfalconstaging.blob.core.windows.net/staging-container/domains/logos/7786/thumb.png?1516785678",
    domain_host: "forexlive.com",
    domain_id: 7786,
    domain_name: "Forexlive",
    duplicatesCount: 0,
    expanded_url: "https://www.forexlive.com/news/!/more-on-the-report-central-banks-eyeing-further-purchases-of-gold-20210706?utm_campaign=cityfalcon&utm_medium=cityfalcon&utm_source=cityfalcon",
    friends_count: null,
    full_text: false,
    id: 413988023,
    imageUrls: ["https://az705044.vo.msecnd.net/20190110/mnuchin-gold.png"],
    lang: "en",
    liked: false,
    limited_content: [],
    paywall: false,
    premium_plan_level: null,
    publishTime: "2021-07-06T03:17:55.000Z",
    publishTimeDiff: 2228.52043362,
    purchased: false,
    readCount: 0,
    registrationRequired: false,
    score: 55,
    showPath: "/news/stories/14c55bfb-5efb-4382-aff8-79809ea7b7a0",
    title: "More on the report central banks eyeing further purchases of gold",
    type: "Story",
    url: "https://www.forexlive.com/news/!/more-on-the-report-central-banks-eyeing-further-purchases-of-gold-20210706?utm_campaign=cityfalcon&utm_medium=cityfalcon&utm_source=cityfalcon",
    user_premium_plans: [],
    uuid: "14c55bfb-5efb-4382-aff8-79809ea7b7a0",
    uuid_title: "14c55bfb-5efb-4382-aff8-79809ea7b7a0-more-on-the-report-central-banks-eyeing-further-purchases-of",
    visibility: null,
    _highlight: null,
    _score: null,
  },
  {
    accessible: true,
    additional_data: {tweet_id: "1412249435837509636"},
    author_followers_count: 267453,
    author_image_url: "http://pbs.twimg.com/profile_images/378800000833266807/9ed4b5e5bffc2e60da94913d51cbd666_normal.png",
    author_screen_name: "ForexLive",
    bookmarked: false,
    can_purchase: false,
    category: "op",
    cost: null,
    description: "A piece posted yesterday on Central banks said to be returning to buying gold Adding a little more to the info in that post, with the World Gold Council saying one in five central banks intend to increase their gold reserves over the next year. By...",
    disliked: false,
    domain_cached_logo_url: "https://cityfalconstaging.blob.core.windows.net/staging-container/domains/logos/7786/thumb.png?1516785678",
    domain_host: "forexlive.com",
    domain_id: 7786,
    domain_name: "Forexlive",
    duplicatesCount: 0,
    expanded_url: "https://www.forexlive.com/news/!/more-on-the-report-central-banks-eyeing-further-purchases-of-gold-20210706?utm_campaign=cityfalcon&utm_medium=cityfalcon&utm_source=cityfalcon",
    friends_count: null,
    full_text: false,
    id: 413988023,
    imageUrls: ["https://az705044.vo.msecnd.net/20190110/mnuchin-gold.png"],
    lang: "en",
    liked: false,
    limited_content: [],
    paywall: false,
    premium_plan_level: null,
    publishTime: "2021-07-06T03:17:55.000Z",
    publishTimeDiff: 2228.52043362,
    purchased: false,
    readCount: 0,
    registrationRequired: false,
    score: 55,
    showPath: "/news/stories/14c55bfb-5efb-4382-aff8-79809ea7b7a0",
    title: "More on the report central banks eyeing further purchases of gold",
    type: "Story",
    url: "https://www.forexlive.com/news/!/more-on-the-report-central-banks-eyeing-further-purchases-of-gold-20210706?utm_campaign=cityfalcon&utm_medium=cityfalcon&utm_source=cityfalcon",
    user_premium_plans: [],
    uuid: "14c55bfb-5efb-4382-aff8-79809ea7b7a0",
    uuid_title: "14c55bfb-5efb-4382-aff8-79809ea7b7a0-more-on-the-report-central-banks-eyeing-further-purchases-of",
    visibility: null,
    _highlight: null,
    _score: null,
  },
  {
    accessible: true,
    additional_data: {tweet_id: "1412249435837509636"},
    author_followers_count: 267453,
    author_image_url: "http://pbs.twimg.com/profile_images/378800000833266807/9ed4b5e5bffc2e60da94913d51cbd666_normal.png",
    author_screen_name: "ForexLive",
    bookmarked: false,
    can_purchase: false,
    category: "op",
    cost: null,
    description: "A piece posted yesterday on Central banks said to be returning to buying gold Adding a little more to the info in that post, with the World Gold Council saying one in five central banks intend to increase their gold reserves over the next year. By...",
    disliked: false,
    domain_cached_logo_url: "https://cityfalconstaging.blob.core.windows.net/staging-container/domains/logos/7786/thumb.png?1516785678",
    domain_host: "forexlive.com",
    domain_id: 7786,
    domain_name: "Forexlive",
    duplicatesCount: 0,
    expanded_url: "https://www.forexlive.com/news/!/more-on-the-report-central-banks-eyeing-further-purchases-of-gold-20210706?utm_campaign=cityfalcon&utm_medium=cityfalcon&utm_source=cityfalcon",
    friends_count: null,
    full_text: false,
    id: 413988023,
    imageUrls: ["https://az705044.vo.msecnd.net/20190110/mnuchin-gold.png"],
    lang: "en",
    liked: false,
    limited_content: [],
    paywall: false,
    premium_plan_level: null,
    publishTime: "2021-07-06T03:17:55.000Z",
    publishTimeDiff: 2228.52043362,
    purchased: false,
    readCount: 0,
    registrationRequired: false,
    score: 55,
    showPath: "/news/stories/14c55bfb-5efb-4382-aff8-79809ea7b7a0",
    title: "More on the report central banks eyeing further purchases of gold",
    type: "Story",
    url: "https://www.forexlive.com/news/!/more-on-the-report-central-banks-eyeing-further-purchases-of-gold-20210706?utm_campaign=cityfalcon&utm_medium=cityfalcon&utm_source=cityfalcon",
    user_premium_plans: [],
    uuid: "14c55bfb-5efb-4382-aff8-79809ea7b7a0",
    uuid_title: "14c55bfb-5efb-4382-aff8-79809ea7b7a0-more-on-the-report-central-banks-eyeing-further-purchases-of",
    visibility: null,
    _highlight: null,
    _score: null,
  },
  {
    accessible: true,
    additional_data: {tweet_id: "1412249435837509636"},
    author_followers_count: 267453,
    author_image_url: "http://pbs.twimg.com/profile_images/378800000833266807/9ed4b5e5bffc2e60da94913d51cbd666_normal.png",
    author_screen_name: "ForexLive",
    bookmarked: false,
    can_purchase: false,
    category: "op",
    cost: null,
    description: "A piece posted yesterday on Central banks said to be returning to buying gold Adding a little more to the info in that post, with the World Gold Council saying one in five central banks intend to increase their gold reserves over the next year. By...",
    disliked: false,
    domain_cached_logo_url: "https://cityfalconstaging.blob.core.windows.net/staging-container/domains/logos/7786/thumb.png?1516785678",
    domain_host: "forexlive.com",
    domain_id: 7786,
    domain_name: "Forexlive",
    duplicatesCount: 0,
    expanded_url: "https://www.forexlive.com/news/!/more-on-the-report-central-banks-eyeing-further-purchases-of-gold-20210706?utm_campaign=cityfalcon&utm_medium=cityfalcon&utm_source=cityfalcon",
    friends_count: null,
    full_text: false,
    id: 413988023,
    imageUrls: ["https://az705044.vo.msecnd.net/20190110/mnuchin-gold.png"],
    lang: "en",
    liked: false,
    limited_content: [],
    paywall: false,
    premium_plan_level: null,
    publishTime: "2021-07-06T03:17:55.000Z",
    publishTimeDiff: 2228.52043362,
    purchased: false,
    readCount: 0,
    registrationRequired: false,
    score: 55,
    showPath: "/news/stories/14c55bfb-5efb-4382-aff8-79809ea7b7a0",
    title: "More on the report central banks eyeing further purchases of gold",
    type: "Story",
    url: "https://www.forexlive.com/news/!/more-on-the-report-central-banks-eyeing-further-purchases-of-gold-20210706?utm_campaign=cityfalcon&utm_medium=cityfalcon&utm_source=cityfalcon",
    user_premium_plans: [],
    uuid: "14c55bfb-5efb-4382-aff8-79809ea7b7a0",
    uuid_title: "14c55bfb-5efb-4382-aff8-79809ea7b7a0-more-on-the-report-central-banks-eyeing-further-purchases-of",
    visibility: null,
    _highlight: null,
    _score: null,
  },
  {
    accessible: true,
    additional_data: {tweet_id: "1412249435837509636"},
    author_followers_count: 267453,
    author_image_url: "http://pbs.twimg.com/profile_images/378800000833266807/9ed4b5e5bffc2e60da94913d51cbd666_normal.png",
    author_screen_name: "ForexLive",
    bookmarked: false,
    can_purchase: false,
    category: "op",
    cost: null,
    description: "A piece posted yesterday on Central banks said to be returning to buying gold Adding a little more to the info in that post, with the World Gold Council saying one in five central banks intend to increase their gold reserves over the next year. By...",
    disliked: false,
    domain_cached_logo_url: "https://cityfalconstaging.blob.core.windows.net/staging-container/domains/logos/7786/thumb.png?1516785678",
    domain_host: "forexlive.com",
    domain_id: 7786,
    domain_name: "Forexlive",
    duplicatesCount: 0,
    expanded_url: "https://www.forexlive.com/news/!/more-on-the-report-central-banks-eyeing-further-purchases-of-gold-20210706?utm_campaign=cityfalcon&utm_medium=cityfalcon&utm_source=cityfalcon",
    friends_count: null,
    full_text: false,
    id: 413988023,
    imageUrls: ["https://az705044.vo.msecnd.net/20190110/mnuchin-gold.png"],
    lang: "en",
    liked: false,
    limited_content: [],
    paywall: false,
    premium_plan_level: null,
    publishTime: "2021-07-06T03:17:55.000Z",
    publishTimeDiff: 2228.52043362,
    purchased: false,
    readCount: 0,
    registrationRequired: false,
    score: 55,
    showPath: "/news/stories/14c55bfb-5efb-4382-aff8-79809ea7b7a0",
    title: "More on the report central banks eyeing further purchases of gold",
    type: "Story",
    url: "https://www.forexlive.com/news/!/more-on-the-report-central-banks-eyeing-further-purchases-of-gold-20210706?utm_campaign=cityfalcon&utm_medium=cityfalcon&utm_source=cityfalcon",
    user_premium_plans: [],
    uuid: "14c55bfb-5efb-4382-aff8-79809ea7b7a0",
    uuid_title: "14c55bfb-5efb-4382-aff8-79809ea7b7a0-more-on-the-report-central-banks-eyeing-further-purchases-of",
    visibility: null,
    _highlight: null,
    _score: null,
  },
];
